# Generated by Django 3.2.4 on 2022-04-05 17:14

from django.db import migrations, models
import nft_token.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_hash', models.CharField(default=nft_token.models.create_hash, max_length=20, unique=True)),
                ('tx_hash', models.CharField(max_length=50, unique=True)),
                ('media_url', models.CharField(default='https://squeaksandnibbles.com/wp-content/uploads/2018/02/Peruvian-Guinea-Pig-Breed-Information-SN-long.jpg', max_length=200)),
                ('owner', models.CharField(max_length=50)),
            ],
        ),
    ]
