# Generated by Django 3.1 on 2022-04-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_token', '0002_auto_20220406_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='tx_hash',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
