version: "3.3"

services:
  db:
    image: postgres:12.0-alpine
    env_file:
      - .env
    container_name: bntm_db
    volumes:
      - bntm_db:/var/lib/postgresql/data

  redis:
    image: redis:rc-alpine
    container_name: bntm_redis

  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: bntm_web
    volumes:
      - ./:/usr/src/app/
    env_file:
      - .env
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis


volumes:
  bntm_db: